import { Router, Request, Response } from 'express';
import JSZip from 'jszip';
import { createClient } from '@supabase/supabase-js';

const router = Router();

function htmlToJsx(html: string): string {
  return html
    .replace(/\bclass=/g, 'className=')
    .replace(/\bfor=/g, 'htmlFor=')
    .replace(/<br(\s*)\/?>/gi, '<br />')
    .replace(/<hr(\s*)\/?>/gi, '<hr />')
    .replace(/<img([^>]*)(?<!\/)>/gi, '<img$1 />')
    .replace(/<input([^>]*)(?<!\/)>/gi, '<input$1 />')
    .replace(/<meta([^>]*)(?<!\/)>/gi, '<meta$1 />')
    .replace(/<link([^>]*)(?<!\/)>/gi, '<link$1 />');
}

router.post('/react', async (req: Request, res: Response) => {
  // Auth check
  const authHeader = req.headers.authorization;
  if (!authHeader) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const token = authHeader.replace('Bearer ', '');

  const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
  const { data: { user }, error: authError } = await supabase.auth.getUser(token);
  if (authError || !user) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }

  // Pro check
  const { data: profile } = await supabase
    .from('profiles')
    .select('is_pro')
    .eq('id', user.id)
    .single();

  if (!profile?.is_pro) {
    res.status(403).json({ error: 'Pro plan required for React export' });
    return;
  }

  const { html } = req.body as { html: string };
  if (!html || typeof html !== 'string') {
    res.status(400).json({ error: 'Missing html field' });
    return;
  }

  const jsx = htmlToJsx(html);
  const escaped = jsx.replace(/`/g, '\\`').replace(/\$/g, '\\$');

  const appJsx = `import React from 'react';

export default function App() {
  return (
    <div dangerouslySetInnerHTML={{ __html: \`${escaped}\` }} />
  );
}
`;

  const packageJson = JSON.stringify({
    name: 'volta-export',
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies: {
      react: '^18.2.0',
      'react-dom': '^18.2.0',
    },
    devDependencies: {
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      '@vitejs/plugin-react': '^4.0.0',
      tailwindcss: '^3.4.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0',
      typescript: '^5.0.0',
      vite: '^5.0.0',
    },
  }, null, 2);

  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
`;

  const readme = `# Volta Export

Generated by [Volta](https://volta.build) — AI website builder.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173 to view your site.
`;

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Volta Export</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  const mainTsx = `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
`;

  const zip = new JSZip();
  zip.file('src/App.jsx', appJsx);
  zip.file('src/main.tsx', mainTsx);
  zip.file('index.html', indexHtml);
  zip.file('package.json', packageJson);
  zip.file('tailwind.config.js', tailwindConfig);
  zip.file('README.md', readme);

  const buffer = await zip.generateAsync({ type: 'nodebuffer' });

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', 'attachment; filename="volta-react-export.zip"');
  res.send(buffer);
});

export default router;
